// SPDX-FileCopyrightText: 2023 Greenbone AG
//
// SPDX-License-Identifier: GPL-3.0-or-later

package opensight_golang_libraries

// THIS IS AN AUTOGENERATED FILE. DO NOT TOUCH!

var Version = "1.11.3-alpha5-dev1"
