// SPDX-FileCopyrightText: 2023 Greenbone AG
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Copyright (C) Greenbone Networks GmbH
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package opensight_golang_libraries

// THIS IS AN AUTOGENERATED FILE. DO NOT TOUCH!

var Version = "0.0.2-alpha2-dev1"
