services:
  opensearch-test:
      image: opensearchproject/opensearch:2.19.3
      environment:
        - cluster.name=opensearch-cluster
        - node.name=opensearch-test
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - cluster.routing.allocation.disk.watermark.low=0.97 # set all watermarks very high, as the CI runners and some dev systems are very limited in disk space ...
        - cluster.routing.allocation.disk.watermark.high=0.99 # ... but don't disable it completely, so that we still get proper warnings in the log
        - cluster.routing.allocation.disk.watermark.flood_stage=0.995
        - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
        - OPENSEARCH_INITIAL_ADMIN_PASSWORD=secureTestPassword444!
      volumes:
        - opensearch-data-test:/usr/share/opensearch/data
      ports:
        - 9300:9200
      healthcheck:
        # verbose for the local setup
        test: ["CMD-SHELL", "curl -k -u admin:secureTestPassword444! --no-progress-meter --fail-with-body https://localhost:9200/_cluster/health && echo ' -- health probe succeeded'"]
        interval: 10s
        timeout: 10s
        retries: 15

volumes:
  opensearch-data-test:
