name: 'Go setup'
description: 'Setup go and cache and go download mods'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        cache: true
        cache-dependency-path: go.sum
        go-version-file: go.mod
