name: 'Go setup'
description: 'Setup go and cache, setup private repo access and go download mods'

inputs:
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
        cache: true
        cache-dependency-path: go.sum
        #go-version-file: go.mod

    - run: git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - run: go mod download
      shell: bash
      env:
        GOPRIVATE: github.com/greenbone
      
