// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthClient creates a new instance of AuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthClient {
	mock := &AuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthClient is an autogenerated mock type for the AuthClient type
type AuthClient struct {
	mock.Mock
}

type AuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthClient) EXPECT() *AuthClient_Expecter {
	return &AuthClient_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type AuthClient
func (_mock *AuthClient) GetToken(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthClient_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type AuthClient_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthClient_Expecter) GetToken(ctx interface{}) *AuthClient_GetToken_Call {
	return &AuthClient_GetToken_Call{Call: _e.mock.On("GetToken", ctx)}
}

func (_c *AuthClient_GetToken_Call) Run(run func(ctx context.Context)) *AuthClient_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthClient_GetToken_Call) Return(s string, err error) *AuthClient_GetToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AuthClient_GetToken_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *AuthClient_GetToken_Call {
	_c.Call.Return(run)
	return _c
}
