name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/go-setup
      - run: make test-codecov
      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: cov-unit-tests.out
          flags: unit-tests
          name: Unit Tests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  opensearch-test:
    name: Execute Opensearch tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/go-setup
      - name: Execute OpenSearch tests
        run: make test-opensearch
      - name: Upload OpenSearch test coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: cov-os-tests.out
          flags: opensearch-tests
          name: OpenSearch Tests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  postgres-test:
    name: Execute postgres tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/go-setup
      - name: Execute Postgres tests
        run: make test-postgres
      - name: Upload Postgres test coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: cov-pg-tests.out
          flags: postgres-tests
          name: Postgres Tests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
